image: mono:4.6.0.245

stages:
    - build
    - test

before_script:     
    - nuget restore -NonInteractive

release:
    stage: build
    only:
        - master
        - tags
        - triggers
    artifacts:
        paths:
          - Build/Release/Yakka.exe
    script:
        - xbuild "Yakka.sln" /p:Configuration="Release" /p:Platform="Any CPU"

ci-release:
    stage: build
    only:
        - master
    except:
        - tags
        - triggers
    artifacts:
        expire_in: 4 weeks
        paths:
          - Build/Release/Yakka.exe
    script:
        - xbuild "Yakka.sln" /p:Configuration="Release" /p:Platform="Any CPU"
    
ci-debug:
    stage: test
    artifacts:
        expire_in: 1 week
        paths:
          - Build/Debug/Yakka.Test.dll
          - Build/Debug/Yakka.Test/Yakka.exe
          - Build/Debug/Yakka.Test/Yakka.TestReport.xml
    script:
        - xbuild "Yakka.sln" /p:Configuration="Debug" /p:Platform="Any CPU"
        - mono packages/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe Build/Debug/Yakka.Test.dll --work=Build/Debug/ --result=Yakka.TestReport.xml